INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('AC', 'Acre',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('AL', 'Alagoas',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('AP', 'Amapá',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('AM', 'Amazonas',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('BA', 'Bahia',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('CE', 'Ceará',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('DF', 'Distrito Federal',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('ES', 'Espírito Santo',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('GO', 'Goiás',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('MA', 'Maranhão',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('MT', 'Mato Grosso',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('MS', 'Mato Grosso do Sul',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('MG', 'Minas Gerais',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('PA', 'Pará',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('PB', 'Paraíba',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('PR', 'Paraná',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('PE', 'Pernambuco',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('PI', 'Piauí',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('RJ', 'Rio de Janeiro',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('RN', 'Rio Grande do Norte',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('RS', 'Rio Grande do Sul',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('RO', 'Rondônia',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('RR', 'Roraima',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('SC', 'Santa Catarina',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('SP', 'São Paulo',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('SE', 'Sergipe',1);
INSERT INTO estado (`sigla`, `nome`, `pais_id`) VALUES ('TO', 'Tocantins',1);