        </div>
            </div>
                        <script src="<?= ROOT_URL ?>/assets/js/jquery.js" type="text/javascript"></script>
                        <script src="<?= ROOT_URL ?>/assets/js/bootstrap.min.js" type="text/javascript"></script>
                        <script src="<?= ROOT_URL ?>/assets/js/dataTable.js" type="text/javascript"></script>
                        <script src="<?= ROOT_URL ?>/assets/js/scripts.js" defer></script>
                    </body>
                </html>            
            </div> 
        </div>
    </body>
</html>