<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
        <title><?= PROJECT_NAME ?></title>
        <!-- BOOTSTRAP CORE STYLE CSS -->
        <link href="<?= ROOT_URL ?>/assets/css/bootstrap.css" rel="stylesheet" />
        <link href="<?= ROOT_URL ?>/assets/css/style.css" rel="stylesheet" />
        <link href="<?= ROOT_URL ?>/assets/css/bootstrap.min.css" rel="stylesheet"/>
        <link href="<?= ROOT_URL ?>/assets/css/dashboard.css" rel="stylesheet" />
        <link href="<?= ROOT_URL ?>/assets/css/dataTable.css" rel="stylesheet" />
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <?php $urlModalTipo = $this->UrlBuilder()->doAction('tipoBebida', array('salvar' => TRUE)); ?>
        <script>
           var Ajax = {
               url : '<?= ROOT_URL ?>',
               urlModalTipo : '<?= $urlModalTipo ?>'
           }
        </script>
        <script src="<?= ROOT_URL ?>/assets/js/jquery.js" type="text/javascript" defer></script>
        <script src="<?= ROOT_URL ?>/assets/js/bootstrap.min.js" type="text/javascript" defer></script>
        <script src="<?= ROOT_URL ?>/assets/js/dataTable.js" type="text/javascript" defer></script>
        <script src="<?= ROOT_URL ?>/assets/js/mask.js" type="text/javascript" defer></script>
        <script src="<?= ROOT_URL ?>/assets/js/scripts.js" type="text/javascript" defer></script>
         
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= ROOT_URL ?>"><?= PROJECT_NAME ?></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Perfil</a></li>
                        <li><a href="<?= $this->UrlBuilder()->doAction('login', array('logar' => FALSE)); ?>">Logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <ul class="nav nav-sidebar">
                        <li class="active" ><a href="#">Painel</a></li>

                        <li class="">
                            <a href="#">Clientes</a></li>

                        <li class=""><a href="#">Pratos</a></li>
                        
                        <li class=""><a href="<?= $this->UrlBuilder()->doAction('temperos')?>">Temperos</a></li>

                        <li class=""><a href="<?= $this->UrlBuilder()->doAction('ingredientes')?>">Ingredientes</a></li>

                        <li class="">
                            <a href="#">Cardápos</a></li>

                        <li class=""><a href="<?= $this->UrlBuilder()->doAction('bebida')?>">Bebidas</a></li>

                        <li class=""><a href="#">Relatórios</a></li>
                    </ul>
                    <ul class="nav nav-sidebar">
                        <li class=""><a href="<?= $this->UrlBuilder()->doAction('pessoa') ?>">Pessoa</a></li>
                        <li class=""><a href="#">Site</a></li>
                    </ul>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">