<?php

use Delivery\Helpers\SessionHandler as SessionHandler;
use Delivery\Dao\ClienteDao as ClienteDao;

if (SessionHandler::checkSession('cliente')) {
    
    $where = SessionHandler::selectSession('cliente');
    $clienteDao = new ClienteDao();
    $cliente = $clienteDao->obterCliente($where);

    if(@$cliente->getNome() != ""){
        $nomeCompleto = $cliente->getNome();
        $nome = substr($nomeCompleto, 0, strpos($nomeCompleto, " "));
        if($nome == ""){
            $nome = $nomeCompleto;
        }
    }
}
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
        <title><?= PROJECT_NAME ?></title>
        <!-- BOOTSTRAP CORE STYLE CSS -->
        <link href="<?= ROOT_URL ?>/assets/css/bootstrap.css" rel="stylesheet" />
        <link href="<?= ROOT_URL ?>/assets/css/carousel.css" rel="stylesheet" />
        <link href="<?= ROOT_URL ?>/assets/css/style.css" rel="stylesheet" />
        <link href="<?= ROOT_URL ?>/assets/css/bootstrap.min.css" rel="stylesheet"/>
        <link href="<?= ROOT_URL ?>/assets/css/dashboard.css" rel="stylesheet" />
        <link href="<?= ROOT_URL ?>/assets/css/dataTable.css" rel="stylesheet" />
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
<?php $urlModalTipo = $this->UrlBuilder()->doAction('tipoBebida', array('salvar' => TRUE)); ?>
<?php $urlModalStatusPrato = $this->UrlBuilder()->doAction('statusPrato', array('salvar' => TRUE)); ?>
<?php $urlModalTipoPrato = $this->UrlBuilder()->doAction('tipoPrato', array('salvar' => TRUE)); ?>
<?php $urlModalTamanhoPrato = $this->UrlBuilder()->doAction('tamanhoPrato', array('salvar' => TRUE)); ?>
        
        <script>
            var Ajax = {
                url: '<?= ROOT_URL ?>',
                urlModalTipo: '<?= $urlModalTipo ?>',
                urlModalStatusPrato: '<?= $urlModalStatusPrato ?>',
                urlModalTipoPrato: '<?= $urlModalTipoPrato ?>',
                urlModalTamanhoPrato: '<?= $urlModalTamanhoPrato ?>'
            }
        </script>
        <script src="<?= ROOT_URL ?>/assets/js/jquery.js" type="text/javascript" defer></script>
        <script src="<?= ROOT_URL ?>/assets/js/bootstrap.min.js" type="text/javascript" defer></script>
        <script src="<?= ROOT_URL ?>/assets/js/dataTable.js" type="text/javascript" defer></script>
        <script src="<?= ROOT_URL ?>/assets/js/mask.js" type="text/javascript" defer></script>
        <script src="<?= ROOT_URL ?>/assets/js/scripts.js" type="text/javascript" defer></script>

    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= ROOT_URL ?>"><?= PROJECT_NAME ?></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <?php if(isset($nome) && $nome != "") :?>
                        <li><a href = "#"><?= "Ola " . $nome ?></a></li>
                       <?php endif; ?>
                        <?php if(!SessionHandler::selectSession('usuario')) : ?>
                            <li><a href="<?= $this->UrlBuilder()->doAction('pedido'); ?>">Fazer Pedido</a></li>
                            <li><a href="<?= $this->UrlBuilder()->doAction('cliente'); ?>">Login</a></li>
                        <?php endif; ?>
                        <li><a href="<?= $this->UrlBuilder()->doAction('admin'); ?>">Adm</a></li>
                        <li><a href="<?= $this->UrlBuilder()->doAction('login', array('logar' => FALSE)); ?>">Logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <?php if (!$this->template->carousel) : ?>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 <?= $this->template->menu ? "col-md-offset-2" : "col-md-offset-1" ?> main">
                <?php endif; ?>
