<?php
$url = $this->UrlBuilder()->doAction('temperos', array('salvar' => TRUE));

$temperos = new Delivery\Model\Temperos();

if (isset($this->params['temperoS'])) {
    $temperos = unserialize($this->params['temperoS']);
}

$this->loadHeader();
?>

<?php Delivery\Utils\Utils::displayNotices(); ?>
<form class="form-horizontal" role="form" method="POST" action="<?= $url ?>">

    <div class="form-group">
        <label for="descricao" class="col-sm-2 control-label">* Descricao</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" id="descricao" name="descricao" required placeholder="Descrição..." value="<?= $temperos->getDescricao(); ?>">
        </div>
    </div>

    <?php if ($temperos->getId()) : ?>
        <input type="hidden" class="form-control" id="id" required name="id" placeholder="" value="<?= $temperos->getId() ?>" >
    <?php endif; ?>

    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-8">
            <button type="submit" name="salvar" class="btn btn-primary">Salvar</button>
        </div>
    </div>

</form>

<?php
$this->loadFooter();
?>
