<?php
    use Delivery\Dao\ClienteDao;
    use Delivery\Model\Cliente;
    $url = $this->UrlBuilder()->doAction('cliente', array('adicionar' => TRUE));
    $this->loadHeader(TRUE);
    $clienteDao = new ClienteDao();
    $clientes = $clienteDao->obterCliente(null, TRUE);
    var_dump($clientes['id']);
?>

<?php Delivery\Utils\Utils::displayNotices(); ?>
<h1 class="page-header">Clientes 
    
    <a href="<?=$url?>" class="btn btn-primary">Adicionar</a></h1>
    
    <?php if (isset($this->params['erro'])) : ?>
        <p class="bg-warning"> <?= $this->params['erro']; ?> </p>
    <?php endif; ?>

        <table class="table table-bordered " id="cooks-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Data nascimento</th>
            <th>CPF</th>
            <th>Sexo</th>
            <th>Celular</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <?php if($clientes):?>
        <?php foreach ($clientes as $cliente) :?>
        <tr>
            <td><?= $clientes['id'] ?></td>
            <td><?= $clientes['nome'] ?></td>
            <td><?= $clientes['data_nascimento'] == '' ? '' : date('d/m/Y', strtotime($cliente['data_nascimento'])) ?></td>
            <td><?= $clientes['cpf'] ?></td>
            <td><?= $clientes['sexo'] ?></td>
            <td><?= $clientes['celular'] ?></td>
            <td><?= $clientes['email'] ?></td>
            <td><a href="<?= $this->UrlBuilder()->doAction('pessoa', array('editar' => TRUE, 
                'id' => "{$clientes['id']}"));?>" class="btn btn-info">Editar</a>
                <a href="<?= $this->UrlBuilder()->doAction('pessoa', array('remover' => TRUE, 
                'id' => "{$clientes['id']}"));?>" class="btn btn-danger">Remover</a>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>
<?php $this->loadFooter();?>