<?php
$url = $this->UrlBuilder()->doAction('prato', array('salvar' => TRUE));

$urlStausPrato = $this->UrlBuilder()->doAction('combo', array('statusPrato' => TRUE));
$urlTipoPrato = $this->UrlBuilder()->doAction('combo', array('tipoPrato' => TRUE));
$urlTamanhoPrato = $this->UrlBuilder()->doAction('combo', array('tamanhoPrato' => TRUE));

$prato = new Delivery\Model\Prato();

if (isset($this->params['pratoS'])) {
    $prato = unserialize($this->params['pratoS']);
}

$tipo_prato = $this->getTipoPrato();
$status_prato = $this->getStatusPrato();
$tamanho_prato = $this->getTamanhoPrato();

$this->loadHeader(TRUE);
?>

<?php Delivery\Utils\Utils::displayNotices(); ?>
<form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data" action="<?= $url ?>">

    <div class="form-group">
        <label for="nome" class="col-sm-2 control-label">* Nome</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" id="nome" name="nome" required placeholder="Nome..." value="<?= $prato->getNome(); ?>">
        </div>
    </div>
    
    <div class="form-group">
        <label for="descricao" class="col-sm-2 control-label">* Descricao</label>
        <div class="col-sm-3">
            <textarea type="text" class="form-control" id="descricao" name="descricao" required placeholder="Descrição..." value="<?= $prato->getDescricao(); ?>">
            </textarea>
        </div>
    </div>

    <div class="form-group">
        <label for="preco" class="col-sm-2 control-label">* Preço</label>
        <div class="col-sm-3">
            <input type="text" class="form-control mask-preco" id="preco" name="preco" required placeholder="Preço..." value="<?= $prato->getPreco(); ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="prato" class="col-sm-2 control-label">* Status do Prato</label>
        <div class="col-sm-3 input-group" name="statusPrato" id="statusPrato">
            <select class="form-control" id="status_prato_id" name="status_prato_id" required>
                <option value="0">Selecione</option>
                <?php foreach ($status_prato as $status): ?>
                    <option value="<?= $status['id'] ?>" <?php if ($status['id'] == $prato->getStatus_prato_id()) { ?> selected="selected" <?php } ?>><?= $status['descricao'] ?> </option>
                <?php endforeach; ?>
            </select>
            <span class="input-group-btn">
                <button class="btn btn-default" data-toggle="modal" data-target="#statusPratoModal" type="button">+</button>
            </span>
        </div>
    </div>

    <div class="form-group">
        <label for="prato" class="col-sm-2 control-label">* Tipo de Prato</label>
        <div class="col-sm-3 input-group" name="tipoPrato" id="tipoPrato">
            <select class="form-control" id="tipo_prato_id" name="tipo_prato_id" required>
                <option value="0">Selecione</option>
                <?php foreach ($tipo_prato as $tipo): ?>
                    <option value="<?= $tipo['id'] ?>" <?php if ($tipo['id'] == $prato->getTipo_prato_id()) { ?> selected="selected" <?php } ?>><?= $tipo['descricao'] ?> </option>
                <?php endforeach; ?>
            </select>
            <span class="input-group-btn">
                <button class="btn btn-default" data-toggle="modal" data-target="#tipoPratoModal" type="button">+</button>
            </span>
        </div>
    </div>
    
    <div class="form-group">
        <label for="prato" class="col-sm-2 control-label">* Tamanho do Prato</label>
        <div class="col-sm-3 input-group" name="tamanhoPrato" id="tamanhoPrato">
            <select class="form-control" id="tamanho_prato_id" name="tamanho_prato_id" required>
                <option value="0">Selecione</option>
                <?php foreach ($tamanho_prato as $tamanho): ?>
                    <option value="<?= $tamanho['id'] ?>" <?php if ($tamanho['id'] == $prato->getTamanho_prato_id()) { ?> selected="selected" <?php } ?>><?= $tamanho['descricao'] ?> </option>
                <?php endforeach; ?>
            </select>
            <span class="input-group-btn">
                <button class="btn btn-default" data-toggle="modal" data-target="#tamanhoPratoModal" type="button">+</button>
            </span>
        </div>
    </div>

    <div class="form-group">
        <label for="image" class="col-sm-2 control-label">* Imagem</label>
        <div class="col-sm-3">
            <input type="file" class="form-control" id="preco" name="imagem" placeholder="Imagem..." value="">
        </div>
    </div>

    <?php if ($prato->getId()) : ?>
        <input type="hidden" class="form-control" id="id" required name="id" placeholder="" value="<?= $prato->getId() ?>" >
        <input type="hidden" class="form-control" id="imagem_prato_id" required name="imagem_prato_id" placeholder="" value="<?= $prato->getImagem_prato_id() ?>" >
    <?php endif; ?>

    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-8">
            <button type="submit" name="salvar" class="btn btn-primary">Salvar</button>
        </div>
    </div>

</form>

<div class="modal fade" id="statusPratoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Adicione um novo staus para o prato</h4>
                <div id="respostaStatus">

                </div>
            </div>
            <div class="modal-body">
                <form role="form" method="POST" id="statusPrato">
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Descrição:</label>
                        <input type="text" class="form-control" id="status_prato_descricao" name="status_prato_descricao" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" 
                        data-dismiss="modal" id="fecharModalStatusPrato" onclick="buscarStatusPrato('<?= $urlStausPrato ?>')">Fechar</button>
                <button type="button" class="btn btn-primary" id="salvarStatusPrato">Salvar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="tipoPratoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Adicione um novo tipo para o prato</h4>
                <div id="respostaTipo">

                </div>
            </div>
            <div class="modal-body">
                <form role="form" method="POST" id="tipoPrato">
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Descrição:</label>
                        <input type="text" class="form-control" id="tipo_prato_descricao" name="tipo_prato_descricao" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" 
                        data-dismiss="modal" id="fecharModalTipoPrato" onclick="buscarTipoPrato('<?= $urlTipoPrato ?>')">Fechar</button>
                <button type="button" class="btn btn-primary" id="salvarTipoPrato">Salvar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="tamanhoPratoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Adicione um novo tamanho para o prato</h4>
                <div id="respostaTamanho">

                </div>
            </div>
            <div class="modal-body">
                <form role="form" method="POST" id="tamanhoPrato">
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">Descrição:</label>
                        <input type="text" class="form-control" id="tamanho_prato_descricao" name="tamanho_prato_descricao" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" 
                        data-dismiss="modal" id="fecharModalTamanhoPrato" onclick="buscarTamanhoPrato('<?= $urlTamanhoPrato ?>')">Fechar</button>
                <button type="button" class="btn btn-primary" id="salvarTamanhoPrato">Salvar</button>
            </div>
        </div>
    </div>
</div>
<?php
$this->loadFooter();
?>
