<?php
$url = $this->UrlBuilder()->doAction('prato', array('adicionar' => TRUE));
$this->loadHeader(TRUE);
$pratoDao = new \Delivery\Dao\PratoDao();
$pratos = $pratoDao->obterPratos();
?>

<?php Delivery\Utils\Utils::displayNotices(); ?>
<h1 class="page-header">Pratos

    <a href="<?= $url ?>" class="btn btn-primary">Adicionar</a></h1>

<?php if (isset($this->params['erro'])) : ?>
    <p class="bg-warning"> <?= $this->params['erro']; ?> </p>
<?php endif; ?>

<table class="table table-bordered " id="cooks-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Tipo</th>
            <th>Tamanho</th>
            <th>Imagem</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <?php if ($pratos): ?>
            <?php foreach ($pratos as $prato) : ?>
                <tr>
                    <td><?= $prato['id'] ?></td>
                    <td><?= $prato['descricao'] ?></td>
                    <td><?= $prato['preco'] ?></td>
                    <td><?= $prato['tipo'] ?></td>
                    <td><?= $prato['tamanho'] ?></td>
                    <td> <img src="<?= $prato['imagem'] ?>" /></td>
                    <td><a href="<?=
                        $this->UrlBuilder()->doAction('prato', array('editar' => TRUE,
                            'id' => "{$prato['id']}"));
                        ?>" class="btn btn-info">Editar</a>
                        <a href="<?=
                        $this->UrlBuilder()->doAction('prato', array('remover' => TRUE,
                            'id' => "{$prato['id']}"));
                        ?>" class="btn btn-danger">Remover</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>
<?php $this->loadFooter(); ?>