<?php
$url = $this->UrlBuilder()->doAction('pessoa', ['salvar' => TRUE]);
$this->loadHeader();
$estados = $this->getEstados();
$cidades = $this->getCidades(1);
$bairros = $this->getBairros(455);
?>
<form class="form-horizontal" role="form" method="POST" action="<?= $url ?>">

    <div class="form-group">
        <label for="nome" class="col-sm-2 control-label">Nome</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="nome" name="nome" required placeholder="Nome..." value="">
        </div>
        <label for="idade" class="col-sm-1 control-label">Idade</label>
        <div class="col-sm-2">
            <input type="number" class="form-control" id="idade" name="idade" required placeholder="Idade..." value="">
        </div>
    </div>

    <div class="form-group">
        <label for="data_nascimento" class="col-sm-2 control-label">Data de nascimento</label>
        <div class="col-sm-4">
            <input type="date" class="form-control" id="data_nascimento" name="data_nascimento" placeholder="Data de nascimento..." value="">
        </div>
        <label for="sexo" class="col-sm-1 control-label">Sexo</label>
        <div class="col-sm-3">
            <select class="form-control" id="sexo" name="sexo">
                <option>Masculino</option>
                <option>Feminino</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="nome_mae" class="col-sm-2 control-label">Nome da mãe</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="nome_mae" name="nome_mae" placeholder="Nome da mãe..." value="">
        </div>
    </div>

    <div class="form-group">
        <label for="email" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-6">
            <input type="email" class="form-control" id="email" required name="email" placeholder="Email" value="" > 
        </div> 
    </div>

    <div class="form-group">
        <label for="cpf" class="col-sm-2 control-label">Cpf</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="cpf" required name="cpf" placeholder="CPF..." value="" > 
        </div> 
        <label for="rg" class="col-sm-1 control-label">RG</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="rg" required name="rg" placeholder="RG..." value="" > 
        </div>
    </div>

    <div class="form-group">
        <label for="celular" class="col-sm-2 control-label">Celular</label>
        <div class="col-sm-4">
            <input type="tel" class="form-control" id="celular" required name="celular" placeholder="Celular" value="" > 
        </div> 
        <label for="telefone" class="col-sm-1 control-label">Telefone</label>
        <div class="col-sm-4">
            <input type="tel" class="form-control" id="telefone" required name="telefone" placeholder="Telefone" value="" > 
        </div>
    </div>

    <div class="form-group">
        <label for="estado_id" class="col-sm-2 control-label">Estado</label>
        <div class="col-sm-2">
            <select class="form-control" id="estado_id" name="estado_id">
                <option value="0">Selecione</option>
                <?php foreach ($estados as $estado) : ?>
                    <option value="<?= $estado['id'] ?>"><?= $estado['sigla'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <label for="cidade_id" class="col-sm-1 control-label">Cidade</label>
        <div class="col-sm-4" name="cidade" id="cidade">
            <select class="form-control" id="cidade_id" name="cidade_id">
                <option value="0">Selecione</option>
                <?php foreach ($cidades as $cidade) : ?>
                    <option value="<?= $cidade['id'] ?>"><?= $cidade['nome'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="bairro_id" class="col-sm-2 control-label">Bairro</label>
        <div class="col-sm-2">
            <select class="form-control" id="bairro_id" name="bairro_id">
                <option value="0">Selecione</option>
                <?php foreach ($bairros as $bairro) : ?>
                    <option value="<?= $bairro['id'] ?>"><?= $bairro['nome'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <label for="Endereco" class="col-sm-1 control-label">Endereço</label>
        <div class="col-sm-4">
            <input type="endereco" class="form-control" id="endereco" required name="endereco" placeholder="Endereço..." value="" > 
        </div>
        <div class="col-sm-2">
            <input type="text" class="form-control" id="n_casa" required name="n_casa" placeholder="Número" value="" > 
        </div>
    </div>
    <div class="form-group">
        <label for="usuario" class="col-sm-2 control-label">Usuário</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="usuario" required name="usuario" placeholder="Usuário..." value="" > 
        </div> 
        <label for="senha" class="col-sm-1 control-label">Senha</label>
        <div class="col-sm-4">
            <input type="password" class="form-control" id="senha" required name="senha" placeholder="Senha..." value="" > 
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-8">
            <button type="submit" name="salvar" class="btn btn-success">Salvar</button>
        </div>
    </div>

</form>
<?php
$this->loadFooter();
?>