<?php
$url = $this->UrlBuilder()->doAction('pessoa', ['salvar' => TRUE]);

$urlAjax = $this->UrlBuilder()->doAction('combo');


$pessoa = new Delivery\Model\Pessoa();
$estado = array(0);

if (isset($this->params['pessoaS'])) {
    $pessoa = unserialize($this->params['pessoaS']);

    $estado = $this->getEstados($pessoa->getCidade_id());
    $cidade = $this->getCidade($pessoa->getCidade_id());
    $bairro = $this->getBairro($pessoa->getBairro_id());
}
$this->loadHeader();
$estados = $this->getEstados();
?>

<?php Delivery\Utils\Utils::displayNotices(); ?>
<form class="form-horizontal" role="form" method="POST" action="<?= $url ?>">

    <div class="form-group">
        <label for="nome" class="col-sm-2 control-label">Nome</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="nome" name="nome" required placeholder="Nome..." value="<?= $pessoa->getNome(); ?>">
        </div>
        <label for="idade" class="col-sm-1 control-label">Idade</label>
        <div class="col-sm-2">
            <input type="number" class="form-control" id="idade" name="idade" required placeholder="Idade..." value="<?= $pessoa->getIdade() ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="data_nascimento" class="col-sm-2 control-label">Data de nascimento</label>
        <div class="col-sm-4">
            <input type="date" class="form-control" id="data_nascimento" name="data_nascimento" placeholder="Data de nascimento..." value="<?= $pessoa->getData_nascimento() ?>">
        </div>
        <label for="sexo" class="col-sm-1 control-label">Sexo</label>
        <div class="col-sm-3">
            <select class="form-control" id="sexo" name="sexo">
                <option>Masculino</option>
                <option>Feminino</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="nome_mae" class="col-sm-2 control-label">Nome da mãe</label>
        <div class="col-sm-6">
            <input type="text" class="form-control" id="nome_mae" name="nome_mae" placeholder="Nome da mãe..." value="<?= $pessoa->getNome_mae() ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="email" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-6">
            <input type="email" class="form-control" id="email" required name="email" placeholder="Email" value="<?= $pessoa->getEmail() ?>" > 
        </div> 
    </div>

    <div class="form-group">
        <label for="cpf" class="col-sm-2 control-label">Cpf</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="cpf" required name="cpf" placeholder="CPF..." value="<?= $pessoa->getCpf() ?>" > 
        </div> 
        <label for="rg" class="col-sm-1 control-label">RG</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="rg" required name="rg" placeholder="RG..." value="<?= $pessoa->getRg() ?>" > 
        </div>
    </div>

    <div class="form-group">
        <label for="celular" class="col-sm-2 control-label">Celular</label>
        <div class="col-sm-4">
            <input type="tel" class="form-control" id="celular" required name="celular" placeholder="Celular" value="<?= $pessoa->getCelular() ?>" > 
        </div> 
        <label for="telefone" class="col-sm-1 control-label">Telefone</label>
        <div class="col-sm-4">
            <input type="tel" class="form-control" id="telefone" required name="telefone" placeholder="Telefone" value="<?= $pessoa->getTelefone() ?>" > 
        </div>
    </div>

    <div class="form-group">
        <label for="estado_id" class="col-sm-2 control-label">Estado</label>
        <div class="col-sm-2">
            <select class="form-control" id="s_estado" name="estado" onchange="buscarCidades('<?= $urlAjax ?>', 'cidade select')">
                <option value="0">Selecione</option>
                <?php
                foreach ($estados as $est):?>
                    <option value="<?= $est['id'] ?>" <?php if($estado[0]['id']==$est['id']) { ?> selected="selected"<?php } ?>><?= $est['sigla'] ?></option>
                
                <?php endforeach;?>
            </select>
        </div>
        <label for="cidade_id" class="col-sm-1 control-label">Cidade</label>
        <div class="col-sm-4" name="cidade" id="cidade">
            <select class="form-control" id="s_cidade" name="cidade_id" onchange="buscarBairros('<?= $urlAjax ?>', 'bairro select')">
                <option value="0">Selecione</option>
                <?php if (isset($cidade)): ?>
                    <option value="<?= $cidade[0]['id'] ?>" <?php if($cidade[0]['id']) { ?> selected="selected"<?php } ?>><?= $cidade[0]['nome'] ?></option>
                <?php endif ;?>    
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="bairro_id" class="col-sm-2 control-label">Bairro</label>
        <div class="col-sm-2" id="bairro">
            <select class="form-control" id="s_bairro" name="bairro_id">
                <option value="0">Selecione</option>
                <?php if (isset($bairro)): ?>
                    <option value="<?= $bairro[0]['id'] ?>" <?php if($bairro[0]['id']) { ?> selected="selected"<?php } ?>><?= $bairro[0]['nome'] ?></option>
                <?php endif ;?>
            </select>
        </div>
        <label for="Endereco" class="col-sm-1 control-label">Endereço</label>
        <div class="col-sm-4">
            <input type="endereco" class="form-control" id="endereco" required name="endereco" placeholder="Endereço..." value="<?= $pessoa->getEndereco() ?>" > 
        </div>
        <div class="col-sm-2">
            <input type="text" class="form-control" id="n_casa" required name="n_casa" placeholder="Número" value="" > 
        </div>
    </div>
    <?php if ($pessoa->getId()) : ?>
        <input type="hidden" class="form-control" id="id" required name="id" placeholder="" value="<?= $pessoa->getId() ?>" > 
    <?php endif; ?>
    <!-- 
    <label for="senha" class="col-sm-1 control-label">Senha</label>
    <div class="col-sm-4">
        <input type="password" class="form-control" id="senha" required name="senha" placeholder="Senha..." value="" > 
    </div>
</div>-->
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-8">
            <button type="submit" name="salvar" class="btn btn-primary">Salvar</button>
        </div>
    </div>

</form>
<?php
$this->loadFooter();
?>
