<?php
    $url = $this->UrlBuilder()->doAction('pessoa', ['adicionar' => TRUE]);
    $this->loadHeader();
?>
<h1 class="page-header">Usuários 
    
    <a href="<?=$url?>" class="btn btn-primary">Adicionar Novo</a></h1>

<table class="table table-bordered wcms-table">
    <thead>
        <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Data nascimento</th>
            <th>CPF</th>
            <th>Sexo</th>
            <th>Celular</th>
            <th>Email</th>
            <th>Usuário</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="#" class="btn btn-info">Editar</a>
                <a href="#" class="btn btn-danger">Remover</a></td>
        </tr>
    </tbody>
</table>
<?php $this->loadFooter();?>