<div class="form-group">
    <label class="control-label">Nome</label>
    <input type="text" class="form-control" aria-label="...">
</div>
<div class="form-group">
    <div class="row">
        <div class="col-lg-1">
            <label class="control-label">Idade</label>
        </div>
        <div class="col-lg-9">
            <div class="input-group">
                <select class="form-control">
                    <?php
                    $i = 17;
                    while ($i < 100) :
                        $i++;
                        ?>
                        <option><?= $i ?></option>
                    <?php endwhile; ?>
                </select>
            </div><!-- /input-group -->
        </div>
    </div><!-- /.row -->
</div>



