<body>
    <?php $url = $this->UrlBuilder()->doAction('login', array('cliente' => true)) ?>
    <div id="boxes">

        <div id="dialog" class="window">
            <a href="#" class="close">Fechar [X]</a><br />
            <div class="row">
                <div class="col-lg-6">
                    <p>Já sou cliente.</p>
                    <p>Efetuar logim.</p>
                    <form class="form-horizontal" id="login" role="form" method="POST" action="">
                        <div class="input-group col-lg-6">
                            <label for="nome" class="control-label" >* E-mail</label>
                            <input type="text" class="form-control" name="email" id="email" aria-label="...">
                        </div><!-- /input-group -->
                        <div class="input-group">
                            <label for="nome" class="control-label" >* Senha</label>
                            <input type="text" class="form-control" name="senha" id="senha" aria-label="...">
                        </div><!-- /input-group -->
                        <div class="form-group">
                            <div class="col-md-4 col-lg-6">
                                </br>
                                <input class="btn btn-primary btn-lg" value="Continuar &raquo;" id="login" name="enviar" type="submit"/>
                                <!--Continuar &raquo;</button>-->
                                <div id="fail">

                                </div>
                            </div>
                        </div>

                    </form>

                </div><!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <p>Sou cliente novo.</p>
                    <p>Quero mo cadastrar.</p>
                    <form class="form-horizontal login" role="form" method="POST" action="">
                        <div class="input-group">
                            <div class="input-group">
                                <label for="nome" class="control-label" required>* E-mail</label>
                                <input type="text" class="form-control" aria-label="...">
                            </div><!-- /input-group -->
                            <div class="input-group">
                                <label for="nome" class="control-label">* Senha</label>
                                <input type="text" class="form-control" aria-label="...">
                            </div>
                            <div class="input-group">
                                <label for="nome" class="control-label">* Repetir senha</label>
                                <input type="text" class="form-control" aria-label="...">
                            </div>
                            <div class="form-group">
                                <div class="col-md-4 col-lg-6">
                                    </br>
                                    <p><a class="btn btn-primary btn-lg" href="#" role="button">Continuar &raquo;</a></p>
                                </div>
                            </div>
                        </div><!-- /input-group -->

                    </form>
                </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
        </div>

        <!-- Janela Modal com caixa de diálogo -->  
        <div id="dialog1" class="window">
            <div class="d-header">
                <input type="text" value="usuario" onclick="this.value = ''"/><br/>
                <input type="password" value="Password" onclick="this.value = ''"/>    
            </div>
            <div class="d-blank"></div>
            <div class="d-login"><input type="image" alt="Login" title="Login"/></div>

        </div>
        <!-- Fim Janela Modal com caixa de diálogo -->  



        <!-- Janela Modal com Bloco de Nota -->
        <div id="dialog2" class="window">
            Então?<br />
            Construir uma <b>Janela Modal Simples</b> com o formato que você quiser é fácil!<br />
            Simples e totalmente personalizável : ) <br /><br />
            <input type="button" value="Fechar" class="close"/>
        </div>
        <!-- Fim Janela Modal com Bloco de Nota -->



        <!-- Máscara para cobrir a tela -->
        <div id="mask"></div>

    </div>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><?= PROJECT_NAME ?></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">

                <form class="navbar-form navbar-right" role="form" method="POST" action="<?= $this->UrlBuilder()->doAction('login', array('cliente' => true)) ?>">
                    <div class="form-group col-lg-6">
                        <a class="btn btn-primary btn-lg" name="modal" href="#dialog" role="button">Entrar</a>
                    </div>
                    <a class="btn-lg" href="<?= $this->UrlBuilder()->doAction('admin') ?>">Adm</a>
                </div>
                <div class="navbar-form navbar-right" >
                    <div class="form-group " id="ola">

                    </div>
                </div>
                </div><!--/.navbar-collapse -->
        </div> 
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1>Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>
        <script>
            $(function () {
                $("input#login").click(function (e) {
                    e.preventDefault();
                    $.ajax({
                        type: "POST",
                        url: "<?= $url ?>",
                        data: $('form#login').serialize(),
                        success: function (msg) {
                            if (msg.search('não') < 0) {
                                $("#mask").hide();
                                $(".window").hide();
                            }else{
                                $("#fail").html(msg);
                            }
                        },
                        error: function () {
                            alert("failure");
                        }
                    });
                    return false;
                });
            });
        </script>


