<?php

use Delivery\Dao\ClienteDao;

$url = $this->UrlBuilder()->doAction('cliente', array('adicionar' => TRUE));
$this->loadHeader();
$pratoDao = new Delivery\Dao\PratoDao();
$pratos = $pratoDao->obterPratos();
?>
<div class="container">
    <!--<div id="resposta"></div>-->    
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
            <p class="pull-right visible-xs">
                <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
            </p>
            <div class="row">
                <?php foreach ($pratos as $prato) : ?>
                    <?php $urlAdicionar = $this->UrlBuilder()->doAction('pedido', array('adicionar' => TRUE, 'prato_id' => $prato['id'])) ?>
                    <?php $urlRemover = $this->UrlBuilder()->doAction('pedido', array('remover' => TRUE, 'prato_id' => $prato['id'])) ?>  
                    <?php $urlFazerPedido = $this->UrlBuilder()->doAction('pedido', array('fazerPedido' => TRUE)) ?>  
                    <?php $urlConfirmarPedido = $this->UrlBuilder()->doAction('pedido', array('confirmarPedido' => TRUE)) ?>  
                    <div class="col-xs-6 col-lg-4">
                        <h2><?= $prato['nome'] ?></h2>
                        <div class="imagemPedido">
                            <p><img src="<?= $prato['imagem'] ?>" /></p>
                        </div>
                        <p><a class="btn btn-default" onclick="adicionaAoCarrinho('<?= $urlAdicionar ?>', 'resposta')" role="button">Adicionar no carrinho</a></p>
                        <p><a class="btn btn-default" onclick="removerDoCarrinho('<?= $urlRemover ?>', 'resposta')" role="button">Remover do carrinho</a></p>
                    </div><!--/.col-xs-6.col-lg-4-->
                <?php endforeach; ?>
            </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="resposta">
            <div class="list-group">
                <div class="form-group">
                    <a class="list-group-item">Informações do pedido</a>
                    <a class="list-group-item active">Valor</a>
                    <input type="text"  required class="form-control" id="usuario" name="usuario"  placeholder="R$ " />
                </div>
                <div class="form-group">
                    <a href="#" class="list-group-item active">Itens</a>
                    <input type="text"  required class="form-control" id="usuario" name="usuario"  placeholder="" />
                </div>
                <div class="btn-group btn-group-justified" role="group" aria-label="...">
                    <div class="btn-group" role="group">
                        <button type="button"  data-toggle="modal" data-target="#modalConfirmarPedido" onclick="fazerPedido('<?= $urlFazerPedido ?>')" class="btn btn-success"><strong> FAZER PEDIDO </strong></button>
                    </div>
                </div>
            </div>
        </div><!--/.sidebar-offcanvas-->
    </div><!--/row-->

    <hr>
    <div class="modal fade" id="modalConfirmarPedido" tabindex="-1" role="dialog" aria-labelledby="modalConfirmarPedido">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" 
                            data-dismiss="modal" id="fecharModalConfirmacao" >Fechar</button>
                            <button type="button" class="btn btn-primary" onclick="confirmarPedido('<?= $urlConfirmarPedido ?>')" id="confirmarPedido"><strong>CONFIRMAR PEDIDO</strong></button>
                </div>
            </div>

        </div>
    </div>

    <footer>
        <p>&copy; 2015 SoftCooks, Inc.</p>
    </footer>

</div><!--/.container-->
<?php $this->loadFooter(); ?>